# Generated by Django 4.0.3 on 2022-05-05 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0003_alter_teammembers_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='members_set',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
