# Generated by Django 3.2.9 on 2021-11-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packagetoken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetoken',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
